add compatibility version for hosted engine dc and cluster
oVirt/ovirt-ansible-hosted-engine-setup pull request #375
Opened 2020-09-15 13:01 UTC by kobihk

in the latest version of 4.4, we have a new data center and cluster compatibility version - 4.5  
by default, we use the latest data center and cluster compatibility version - 4.5
but we need also the option to define the hosted engine to stay with compatibility version 4.4

2020-09-15 13:01 UTC, ovirt-infra commented
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

2020-09-15 15:53 UTC, kobihk commented
verified!!

2020-09-15 15:53 UTC, kobihk commented
@arachmani @eslutsky  could you please CR

2020-09-16 07:50 UTC, mwperina commented
Isn't only ovirt-hosted-engine-setup interacting with this role? If so shouldn't this be exposed/fixed in the  ovirt-hosted-engine-setup instead?

2020-09-16 14:39 UTC, arachmani commented
> Isn't only ovirt-hosted-engine-setup interacting with this role? If so shouldn't this be exposed/fixed in the ovirt-hosted-engine-setup instead?

It is also used when running the playbook directly.

2020-09-17 12:17 UTC, arachmani requested changes
AFAIU, DC and cluster can be different versions, right?
If so let's use different vars and add the limitations to the README.

2020-09-17 18:54 UTC, mwperina commented
Btw hosted-engine-setup has already been moved to https://github.com/ovirt/ovirt-ansible-collection so we are going to archive this repository soon (or at least archive master), so I suggest to move this PR to oVirt Ansible Collection and start switching the automation to use the collection

2020-09-21 10:31 UTC, kobihk commented
Created new PR in:
https://github.com/oVirt/ovirt-ansible-collection/pull/125

@arachmani @mwperina 
maybe it will be better to add a deprecation comment as we have in:
https://github.com/oVirt/ovirt-ansible-repositories/pull/62/files

2020-09-22 15:15 UTC, kobihk commented
merged in:
https://github.com/oVirt/ovirt-ansible-collection/pull/125

2020-10-11 14:39 UTC, kobihk commented
AFAIU the latest versions (4.4.2, 4.4.3) should not support the ansible collections.
so I think we still need to keep this repo updated.

2020-10-12 07:12 UTC, mwperina commented
> AFAIU the latest versions (4.4.2, 4.4.3) should not support the ansible collections.
> so I think we still need to keep this repo updated.
> @mwperina wdyt?

On the contrary, from oVirt 4.4.3 are going to support only ansible 2.9.z with ovirt-ansible-collection, which will obsolete all oVirt modules in ansible core and all previously supported standalone oVirt roles.

2020-10-12 09:48 UTC, mwperina commented
OK, we had an offline discussion and we need to help QE until they will switch automation to Ansible Collection. Asaf/Sandro, could you please merge this backport from collection here?

@arachmani @sandrobonazzola

2020-10-12 09:49 UTC, mwperina approved these changes
+1

2020-10-12 10:22 UTC, arachmani approved these changes

2020-10-12 10:23 UTC, merged

2020-10-12 10:41 UTC, kobihk commented
thank you @mwperina @arachmani @sandrobonazzola